// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWVo1hv15yi3eze6_pDicna_iFgPS1ixc',
    appId: '1:515567098215:web:846903cd1253ee29f4b7c2',
    messagingSenderId: '515567098215',
    projectId: 'ecommerce-flutter-2a39a',
    authDomain: 'ecommerce-flutter-2a39a.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-2a39a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUY3_oGFXiZlYN5uF0vmHIhd2UDIswEp4',
    appId: '1:515567098215:android:62210ed30b2a747ef4b7c2',
    messagingSenderId: '515567098215',
    projectId: 'ecommerce-flutter-2a39a',
    storageBucket: 'ecommerce-flutter-2a39a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3MljpIM25MXa3NX5XUsvjF2nKgk-HgoU',
    appId: '1:515567098215:ios:565ebf3a80db47aaf4b7c2',
    messagingSenderId: '515567098215',
    projectId: 'ecommerce-flutter-2a39a',
    storageBucket: 'ecommerce-flutter-2a39a.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3MljpIM25MXa3NX5XUsvjF2nKgk-HgoU',
    appId: '1:515567098215:ios:012e0bdeadc01daef4b7c2',
    messagingSenderId: '515567098215',
    projectId: 'ecommerce-flutter-2a39a',
    storageBucket: 'ecommerce-flutter-2a39a.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
